### ISSUE TITLE
[feature request] Add WikiLink

### ISSUE THREAD

**Issue by shellRaining** [hukkin/mdformat-gfm#32]
very thanks for your useful plugin first! these days I encounter some trouble when formating wikiLink markdown file, for example

```markdown
[[some page]]
```
after format this file, this change to

```markdown
\[\[hello\]\]
```

the wikiLink not work properly now...

github wiki now support this format , can you add this feature?

**Comment by KyleKing** [comment]
Interesting, so it looks like the GFM spec (<https://github.github.com/gfm>) does not have wiki links, but when you have the "Markdown" format selected when editing a Wiki page they are converted to internal links anyway and you don't have to switch to something like the MediaWiki edit mode (<https://www.mediawiki.org/wiki/Help:Formatting> from wikicloth of <https://github.com/github/markup>).

Given that the wiki links don't appear to be documented as part of GFM, my first thought is that the feature would need to be a separate package to support users who want the strict implementation of GFM.

However, you're in luck because a package already seems to exist and you can use it today: <https://github.com/tmr232/mdformat-wikilink> 🎉 

Let me know if `mdformat-wikilink` solves your issue

**Comment by shellRaining** [comment]
yes, it does work! but I don't see this plugin in mdformat docs, so maybe I should take a pr for it 😄
